# Generated by Django 5.1.2 on 2024-10-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_prescription_given_by_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ClinicStaff', 'Clinic Staff'), ('KitchenStaff', 'Kitchen Staff')], default='KitchenStaff', max_length=20),
        ),
    ]
