# Generated by Django 5.1.2 on 2024-10-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
